### ISSUE TITLE
Chat control plugins don't work [1.21.8]

### ISSUE THREAD

**Issue by Ghione1** [Teneted/Taiyitist#25]
I'm trying to use plugins to control the chat, but it seems to prioritize the vanilla chat. If there's a vanilla Minecraft command, even if a plugin tries to replace it, the vanilla command will still take priority. For example, when using gamemode 1, it sends a message in its vanilla format even if Essentials is running, which modifies it.

I also can't modify prefixes and suffixes. It seems to also be as if the vanilla chat takes priority, since if I create teams with vanilla commands, the prefixes and suffixes are modified.

[latest.log](https://github.com/user-attachments/files/21943887/latest.log)

**Comment by wdog5734** [comment]
fixed

**Comment by Ghione1** [comment]
It's still not working. Could it be a problem with the Vault plugin? I really don't think so, but I'm considering it as a possibility.

It's a shame because the other plugins work very well, but without controlling the chat, I won't be able to move my server to Taiyilist.

**Comment by wdog5734** [comment]
Please offer the new logs

**Comment by wdog5734** [comment]
if you use essentials,please use minecraft: as prefix to make a try

**Comment by Ghione1** [comment]
If I understood correctly, you mean to edit this line in Essentials like this:

" format: 'minecraft:<{DISPLAYNAME}> {MESSAGE}' "

It still didn't work; I really didn't fully understand how to do what you told me.

If I misspelled it, please send me the corrected config.yml file so I can see how I should set it up.

EssentialsChat seems to work because when I use /gm 1 my name appears with my prefix or however I configured it, but in the chat the vanilla priority is still given.

[latest.log](https://github.com/user-attachments/files/22003632/latest.log)

**Comment by wdog5734** [comment]
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/legacy/LegacyComponentSerializer

**Comment by Ghione1** [comment]
I don't understand. What did you mean by that? I know it's a log error, but I don't know how to fix it.
